# Generated by Django 5.0 on 2024-04-16 12:41

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=videos.models.upload_video_path),
        ),
    ]
