# Generated by Django 4.2.10 on 2024-03-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userpreference_dark_mode_userpreference_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme_preference',
        ),
    ]
