# Generated by Django 4.2.10 on 2024-03-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_profile_theme_preference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
