# Generated by Django 4.0.3 on 2024-04-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='merchant_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
