# Generated by Django 5.0 on 2024-04-16 13:40

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_merchant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=user.models.upload_profile_image_path),
        ),
    ]
