export const POST_QUESTION_REQUEST = 'POST_QUESTION_REQUEST';
export const POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS';
export const POST_QUESTION_FAIL = 'POST_QUESTION_FAIL';

export const POST_REPLY_REQUEST = 'POST_REPLY_REQUEST';
export const POST_REPLY_SUCCESS = 'POST_REPLY_SUCCESS';
export const POST_REPLY_FAIL = 'POST_REPLY_FAIL';

export const LIST_QUESTIONS_REQUEST = 'LIST_QUESTIONS_REQUEST';
export const LIST_QUESTIONS_SUCCESS = 'LIST_QUESTIONS_SUCCESS';
export const LIST_QUESTIONS_FAIL = 'LIST_QUESTIONS_FAIL';


export const LIST_USER_PRODUCT_QUESTIONS_REQUEST = 'LIST_USER_PRODUCT_QUESTIONS_REQUEST';
export const LIST_USER_PRODUCT_QUESTIONS_SUCCESS = 'LIST_USER_PRODUCT_QUESTIONS_SUCCESS';
export const LIST_USER_PRODUCT_QUESTIONS_FAIL = 'LIST_USER_PRODUCT_QUESTIONS_FAIL';