export const POST_QUESTION_REQUEST = 'POST_QUESTION_REQUEST';
export const POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS';
export const POST_QUESTION_FAIL = 'POST_QUESTION_FAIL';

export const POST_REPLY_REQUEST = 'POST_REPLY_REQUEST';
export const POST_REPLY_SUCCESS = 'POST_REPLY_SUCCESS';
export const POST_REPLY_FAIL = 'POST_REPLY_FAIL';