// userConstants.js

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SET_INSTRUCTOR = 'USER_SET_INSTRUCTOR';
export const USER_SET_STUDENT = 'USER_SET_STUDENT';
export const USER_SET_ROLE_FAIL = 'USER_SET_ROLE_FAIL';

//change password
export const USER_CHANGE_PASSWORD_REQUEST = 'USER_CHANGE_PASSWORD_REQUEST';
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_CHANGE_PASSWORD_FAIL = 'USER_CHANGE_PASSWORD_FAIL';

// email pass shit
export const USER_CONFIRM_CHANGE_PASSWORD_REQUEST = 'USER_CONFIRM_CHANGE_PASSWORD_REQUEST';
export const USER_CONFIRM_CHANGE_PASSWORD_SUCCESS = 'USER_CONFIRM_CHANGE_PASSWORD_SUCCESS';
export const USER_CONFIRM_CHANGE_PASSWORD_FAIL = 'USER_CONFIRM_CHANGE_PASSWORD_FAIL';

// send email (email mismo) pass reset
export const USER_REQUEST_RESET_PASSWORD_REQUEST = 'USER_REQUEST_RESET_PASSWORD_REQUEST';
export const USER_REQUEST_RESET_PASSWORD_SUCCESS = 'USER_REQUEST_RESET_PASSWORD_SUCCESS';
export const USER_REQUEST_RESET_PASSWORD_FAIL = 'USER_REQUEST_RESET_PASSWORD_FAIL';


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_VERIFY_OTP_REQUEST = 'USER_VERIFY_OTP_REQUEST';
export const USER_VERIFY_OTP_SUCCESS = 'USER_VERIFY_OTP_SUCCESS';
export const USER_VERIFY_OTP_FAIL = 'USER_VERIFY_OTP_FAIL';

export const USER_RESEND_OTP_REQUEST = 'USER_RESEND_OTP_REQUEST';
export const USER_RESEND_OTP_SUCCESS = 'USER_RESEND_OTP_SUCCESS';
export const USER_RESEND_OTP_FAIL = 'USER_RESEND_OTP_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const THEME_UPDATE_REQUEST = 'THEME_UPDATE_REQUEST';
export const THEME_UPDATE_SUCCESS = 'THEME_UPDATE_SUCCESS';
export const THEME_UPDATE_FAIL = 'THEME_UPDATE_FAIL';


export const USER_FETCH_PROFILE_WITH_PRODUCTS_REQUEST = 'USER_FETCH_PROFILE_WITH_PRODUCTS_REQUEST';
export const USER_FETCH_PROFILE_WITH_PRODUCTS_SUCCESS = 'USER_FETCH_PROFILE_WITH_PRODUCTS_SUCCESS';
export const USER_FETCH_PROFILE_WITH_PRODUCTS_FAIL = 'USER_FETCH_PROFILE_WITH_PRODUCTS_FAIL';
