# Generated by Django 4.2.10 on 2024-03-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='editedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
