# Generated by Django 4.2.10 on 2024-03-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='video',
            new_name='preview_video',
        ),
    ]
