# Generated by Django 4.2.10 on 2024-04-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
