# Generated by Django 4.0.3 on 2024-04-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_product_ispaid_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='merchant_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='taxPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
