# Generated by Django 4.2.10 on 2024-04-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_order_shippingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='base.product'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
