# Generated by Django 5.0 on 2024-04-16 13:40

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_order_product_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=base.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to=base.models.upload_preview_video_path),
        ),
    ]
