# Generated by Django 5.0 on 2024-04-16 13:51

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_product_image_alter_product_preview_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=base.models.upload_image_path),
        ),
    ]
