# Generated by Django 4.2.10 on 2024-04-22 15:01

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveredAt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isDelivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='taxPrice',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='taxPrice',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=base.models.upload_image_path),
        ),
    ]
