# Generated by Django 4.0.3 on 2024-04-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_orderitem_merchant_id_orderitem_taxprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shippingPrice',
        ),
    ]
